import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.mainnav}>
          <ul>
            <Link href="/">
              <li>Home</li>
            </Link>
            <Link href="/about">
              <li>About</li>
            </Link>
            <Link href="/blog">
              <li>Blog</li>
            </Link>
            <Link href="/contact">
              <li>Contact</li>
            </Link>
          </ul>
        </nav>
        <h1 className={styles.title}>Blog Website</h1>

        <p className={styles.description}>A blog for the coder by the coder</p>

        <div className={styles.blogs}>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the weJavascript is a
              language used to design logic for the weJavascript is a language
              used to design logic for the weJavascript is a language used to
              design logic for the we
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1>learn javascript in 2022?</h1>
            <p>
              Javascript is a language used to design logic for the Javascript
              is a language used to design logic for the webJavascript is a
              language used to design logic for the webJavascript is a language
              used to design logic for the webJavascript is a language used to
              design logic for the web
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
